server:
  port: 9191

spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        item-added-events:
          destination: item-queue